import { createHash, randomBytes } from "node:crypto";

/**
 * 32 bytes = 256 bits, exactly as a session token is.
 *
 * This is the number the whole KDF argument below rests on: the secret is
 * generated by the server from a CSPRNG, so there is no dictionary, no
 * structure and no human choice anywhere in it.
 */
export const MACHINE_TOKEN_SECRET_BYTES = 32;

/**
 * Every machine token starts with this.
 *
 * It is not a security boundary — the hash lookup is — and it is not what tells
 * a machine token from a session token on the wire, which is the
 * `Authorization` scheme (see `http/machine-token-header.ts`). It earns its
 * place for two smaller, human reasons:
 *
 * 1. A machine token is the one credential in this system that gets WRITTEN
 *    DOWN: into a compose file, a systemd unit, a `.env`. Whoever finds
 *    `WAYMARK_TOKEN=wmk_...` months later can tell what they are holding
 *    without asking anybody, and a secret scanner can be taught one pattern.
 * 2. It lets the API refuse a string that was never a machine token before it
 *    queries anything at all, which keeps a stolen session token replayed
 *    under the machine scheme from so much as touching the token table.
 */
export const MACHINE_TOKEN_PREFIX = "wmk_";

/** base64url, which is what `randomBytes(...).toString("base64url")` emits. */
const SECRET_PATTERN = /^[A-Za-z0-9_-]+$/u;

export interface IssuedMachineToken {
  /** Printed by the CLI exactly once. The server never stores this. */
  readonly token: string;
  /** What goes in the database, and what a presented token is looked up by. */
  readonly tokenHash: string;
}

export const issueMachineTokenSecret = (): IssuedMachineToken => {
  const token = `${MACHINE_TOKEN_PREFIX}${randomBytes(
    MACHINE_TOKEN_SECRET_BYTES,
  ).toString("base64url")}`;

  return { token, tokenHash: hashMachineTokenSecret(token) };
};

/**
 * SHA-256, deliberately NOT the scrypt that `create-user` hashes passwords
 * with — and this is the decision worth arguing rather than asserting.
 *
 * ## The case for treating it like a password
 *
 * A machine token is long-lived. A password is long-lived. Both sit in a table
 * that somebody might one day dump. On that reading, a machine token deserves
 * the memory-hard KDF a password gets, and SHA-256 looks like a shortcut.
 *
 * ## Why that reading is wrong here
 *
 * A KDF is slow on purpose, and the purpose is to make GUESSING expensive. It
 * buys exactly as much as the secret's search space is small: a human-chosen
 * password lives in a dictionary of maybe 2^40 realistic candidates, so
 * multiplying each guess by 100ms and 64 MiB is what turns a stolen table into
 * a non-event. This secret is 256 uniform random bits from `randomBytes`. There
 * is no dictionary to walk and no structure to exploit, so an attacker holding
 * the hash is facing 2^256 either way and the KDF multiplies a number that is
 * already out of reach by a constant. Longevity changes the WINDOW an attacker
 * has, not the SEARCH SPACE; against 2^256, no window is long enough. That is
 * the same argument `session-token.ts` already makes, and it does not weaken
 * because the credential lives longer.
 *
 * ## What the cost would actually be
 *
 * The other half is where the two credentials genuinely differ. A password is
 * verified once per login — call it once a month per person. A machine token is
 * verified on EVERY request an MCP server makes, which is the whole point of
 * issuing one. `login.ts` already spells out what a memory-hard KDF behind an
 * unmetered endpoint is: "a denial of service primitive pointed at our own
 * server". scrypt at the parameters `create-user` uses is 64 MiB and ~100ms per
 * verification, on a homelab box with 4-5 GiB to spare; an assistant walking an
 * inventory would take the machine down by being used normally.
 *
 * ## The middle ground, and why it was rejected
 *
 * The obvious rescue is to keep scrypt and cache the verified token in memory
 * for a minute or two, so the cost is paid once per window instead of once per
 * request. That was rejected, and the reason is ADR 6: revocation is the real
 * control, and it is immediate. A cache of verified credentials is a second
 * copy of revocation state that lags the first, so `machine-token revoke` would
 * stop meaning "now" and start meaning "within a minute" — on the one credential
 * whose whole justification is that it can be killed without touching a human
 * account. Paying a cost we then have to cache away is how a security decision
 * becomes a liveness bug.
 *
 * ## So what IS the hash for
 *
 * The same thing it is for on a session: a dump of this table must not contain
 * credentials that still work. SHA-256 over 256 random bits does that
 * completely, in one indexed read, with no arena to allocate.
 *
 * The one property a salted KDF would have given us for free and this does not
 * is protection against a lookup that COMPARES digests. There is none: the hash
 * is the unique key, so the database decides equality and no digest of ours is
 * ever compared byte by byte in application code. See
 * `machine-token-repository.ts`.
 */
export const hashMachineTokenSecret = (token: string): string =>
  createHash("sha256").update(token, "utf8").digest("hex");

/**
 * Whether a presented string could ever have been issued here.
 *
 * Structure only. It says nothing about whether the token exists, is revoked or
 * has expired — those are all one single `InvalidMachineToken`, for the reason
 * `InvalidSession` gives.
 */
export const looksLikeMachineToken = (token: string): boolean => {
  if (!token.startsWith(MACHINE_TOKEN_PREFIX)) {
    return false;
  }

  return SECRET_PATTERN.test(token.slice(MACHINE_TOKEN_PREFIX.length));
};
