/**
 * # The one value a passkey ceremony must not be able to replay
 *
 * An authenticator signs a challenge. If the same challenge can be signed
 * twice, an assertion captured once — out of a proxy, a log, a browser
 * extension — becomes a permanent credential, and every other property of
 * WebAuthn stops mattering. A replayable challenge IS the attack.
 *
 * So a challenge here is three things, and each of them is enforced by the
 * statement that consumes it rather than by a handler remembering to check:
 *
 * 1. **Single use**, because consuming it is a `DELETE` that returns what it
 *    deleted. Two requests racing the same ceremony cannot both be served: the
 *    second one deletes nothing and is handed `null`. A `used` column would
 *    have made this a read, a decision and a write, with a window in it.
 * 2. **Short lived**, two minutes, and checked by the same statement.
 * 3. **Bound to the ceremony that issued it**, because the ceremony is part of
 *    the `WHERE`. A challenge issued to register a device cannot be spent
 *    signing in, even if a handler forgot to look — the row does not match.
 *
 * ## Why it is a row rather than something the client holds
 *
 * Because anything the client holds, the client can choose. A signed cookie or
 * a stateless token carrying the challenge would put the value an attacker
 * wants to reuse into the hands of whoever is replaying it, and the server
 * would be checking a signature it had made itself. The one thing that makes
 * "single use" true is somewhere that can forget, and this table is it.
 *
 * ## Why the client gets an id and not the challenge
 *
 * The client sends back a `ceremonyId` alongside the credential, and the
 * server looks the row up by it. The alternative — reading the challenge out
 * of the `clientDataJSON` the client just sent, and using it to look up the
 * expected challenge — works and is common, and it means selecting the
 * expected value out of attacker-controlled bytes. It is safe in practice
 * because the lookup is exact and the row is single-use, but it reads like a
 * circle, and an opaque id costs one string in a body.
 */

export const PasskeyCeremony = {
  Registration: "registration",
  Authentication: "authentication",
} as const;

export type PasskeyCeremony =
  (typeof PasskeyCeremony)[keyof typeof PasskeyCeremony];

export const PASSKEY_CEREMONIES: readonly PasskeyCeremony[] = [
  PasskeyCeremony.Registration,
  PasskeyCeremony.Authentication,
];

/**
 * SQLite has no enum type, so — exactly as `StorageUnit.kind` and
 * `MachineToken.scope` already are — the column is a string and the value is
 * checked on the way OUT of the database rather than trusted.
 */
export const isPasskeyCeremony = (
  candidate: string,
): candidate is PasskeyCeremony =>
  (PASSKEY_CEREMONIES as readonly string[]).includes(candidate);

export interface PasskeyChallenge {
  /**
   * Opaque, random, and what the client sends back. It is not the challenge:
   * addressing a row and signing a value are two jobs, and giving them one
   * string would mean the lookup key travelled through the authenticator.
   */
  readonly id: string;
  readonly ceremony: PasskeyCeremony;
  /** base64url, generated by the library, and what gets signed. */
  readonly challenge: string;
  /**
   * Who this registration is for, or `null` for a sign-in.
   *
   * A sign-in genuinely has nobody yet — that is the point of a discoverable
   * credential — so the column is nullable and the use case checks that a
   * registration's row belongs to the session finishing it.
   */
  readonly userId: string | null;
  readonly createdAt: Date;
  readonly expiresAt: Date;
}

/**
 * Two minutes.
 *
 * The browser's own `timeout` in the options is 60 seconds, and that is the
 * clock a person experiences: the prompt closes itself. This one is twice
 * that, deliberately, so that the honest slow case — reading the prompt,
 * finding the phone, a thumb that takes three goes — is refused by the
 * browser's timer and never by ours, which is the refusal a person can
 * understand. It is still far shorter than a captured ceremony is worth
 * anything for.
 */
export const PASSKEY_CHALLENGE_TTL_MS = 2 * 60 * 1000;
