/**
 * # One visual vocabulary, for two clients that draw it differently
 *
 * There is one API and two clients (README). `@waymark/i18n` is the contract
 * with the person about WORDS; this is the contract with them about what those
 * words look like.
 *
 * ## Why this is a package and not a folder in each app
 *
 * The same reason as the dictionary, and the same evidence. `@waymark/i18n`
 * has never drifted, because `Dictionary` is a type DERIVED from the English
 * object and a missing Spanish key does not compile. The palettes, written
 * twice in two syntaxes with nothing deriving either from the other, drifted
 * exactly as much as nobody was watching — a card whose photo box was sunken
 * on one client and raised on the other, a `danger` button filled on one and
 * outlined on the other, three font sizes on the browser that were not on the
 * scale the browser published. None of it was WRONG next to itself.
 *
 * So the dependency runs one way and only one way:
 *
 *     tokens  ->  web, mobile
 *
 * and it runs beside the others rather than through them:
 *
 *     domain  ->  api-client  ->  i18n  ->  web, mobile
 *
 * `@waymark/domain` is not where this went, deliberately. It has zero runtime
 * dependencies and it is the model of what is in a box; what a box LOOKS like
 * is not a domain fact, and putting a hex value in there would be the first
 * sentence of the argument that eventually puts a React import in there.
 *
 * ## How each client takes it, and why they differ
 *
 * The phone IMPORTS it. `apps/mobile/src/ui/styles/tokens.ts` re-exports these
 * objects, so a colour changed here is a colour changed there with nothing in
 * between — there is no second copy to forget.
 *
 * The browser cannot, because CSS cannot import TypeScript. So its file is
 * GENERATED by `cssText()` and checked in, and a test in the web client
 * compares the file on disk with what this package renders. Editing the CSS by
 * hand fails that test; changing a value here without regenerating fails it
 * too. Different mechanisms, one guarantee: the values cannot disagree and the
 * suite stay green.
 */
export {
  DARK,
  DARK_WEB_ONLY,
  LIGHT,
  LIGHT_WEB_ONLY,
  type ColorName,
  type Palette,
  type WebColorName,
  type WebOnlyName,
  type WebOnlyPalette,
} from "./palette.js";

export {
  BAR_HEIGHT,
  RADIUS,
  SPACE,
  TAP_TARGET,
  TEXT,
  type RadiusStep,
  type SpaceStep,
  type TextStep,
} from "./scale.js";

export {
  AA_BOUNDARY,
  AA_LARGE_TEXT,
  AA_TEXT,
  contrastRatio,
  MEASURED,
  type Measured,
} from "./contrast.js";

export { cssText } from "./css.js";
