import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

/**
 * A directory shaped exactly like `apps/web/dist`, on disk, in a temp dir.
 *
 * Nothing about serving the built client is faked in these tests: the files
 * are real files with the names Vite actually emits, because the whole
 * interesting half of this feature is which NAME gets which cache header.
 * A fixture that invented its own names would have proved the rule against
 * itself.
 */

/** A chunk name Vite emits: eight base64url characters of content hash. */
export const HASHED_SCRIPT = "assets/index-D1lYCQ-q.js";
export const HASHED_STYLESHEET = "assets/index-DFIqwdA1.css";

/**
 * Generated by `vite-plugin-pwa`, content addressed, and at the ROOT rather
 * than under `assets/` — which is why the rule cannot be "everything under
 * assets is immutable".
 */
export const HASHED_WORKBOX = "workbox-63c18b4d.js";

/**
 * The files whose URL keeps serving new bytes after every deploy. `sw.js` is
 * the one that matters most: pinned into a phone's cache it would keep an old
 * app alive for as long as the `max-age` said.
 */
export const SERVICE_WORKER = "sw.js";
export const MANIFEST = "manifest.webmanifest";

/**
 * Names with a dash and digits in them that are NOT content hashes. Every one
 * of these is in the real `dist`, and every one of them would be served
 * `immutable` for a year by a rule that only looked for a dash.
 */
export const UNHASHED_ICON = "icon-192.png";
export const UNHASHED_TOUCH_ICON = "apple-touch-icon.png";

/** Something the shell says that no JSON answer ever would. */
export const SHELL_MARKER = '<div id="root"></div>';

export const SHELL = `<!doctype html>
<html lang="en">
  <head>
    <title>Ariadna</title>
    <script type="module" src="/${HASHED_SCRIPT}"></script>
    <link rel="stylesheet" href="/${HASHED_STYLESHEET}" />
    <link rel="manifest" href="/${MANIFEST}" />
  </head>
  <body>${SHELL_MARKER}</body>
</html>
`;

const FILES: ReadonlyArray<readonly [string, string]> = [
  ["index.html", SHELL],
  [HASHED_SCRIPT, "console.log('the app');\n"],
  [HASHED_STYLESHEET, ":root { color-scheme: dark; }\n"],
  [HASHED_WORKBOX, "self.workbox = true;\n"],
  [SERVICE_WORKER, "self.addEventListener('install', () => {});\n"],
  [MANIFEST, '{ "name": "Ariadna" }\n'],
  [UNHASHED_ICON, "not really a png\n"],
  [UNHASHED_TOUCH_ICON, "not really a png either\n"],
  ["favicon.svg", "<svg xmlns='http://www.w3.org/2000/svg' />\n"],
];

/** Writes the fixture and answers its root. */
export const createWebRootFixture = async (): Promise<string> => {
  const root = await mkdtemp(join(tmpdir(), "ariadna-web-root-"));
  await mkdir(join(root, "assets"), { recursive: true });

  for (const [path, contents] of FILES) {
    await writeFile(join(root, path), contents, "utf8");
  }

  return root;
};

/**
 * A file OUTSIDE the served root, next to it, holding something a traversal
 * would be trying to reach.
 */
export const createSecretBesideWebRoot = async (
  root: string,
): Promise<string> => {
  const secret = join(root, "..", "ariadna-secret.txt");
  await writeFile(secret, "the session table\n", "utf8");

  return secret;
};
